export const environment = {
  production: false,
  APIURL: "https://apicrm.vnptvungtau.vn/api/v1/",
  APIRootURL: "https://apicrm.vnptvungtau.vn/",
  APIUploadURL: "https://api.upload.vnptvungtau.vn/api/v1/",
  APIUploadRootURL: "https://api.upload.vnptvungtau.vn/",
  LoginURL: "https://login.vnptvungtau.vn/",
  Website: "https://vnptvungtau.vn/",
  Token: "Token",
  TokenAPI: "040621fe-7999-410c-8e06-a3ba249ded43",
  LoadingFile: "loading.gif",
  PanelClass: "full-screen-modal",
  DialogConfigWidth: "90%",
  DialogConfigWidth60: "60%",
  InitializationString: "",
  InitializationNumber: 0,
  NhanVienID: "NhanVienID",
  NhanVienName: "NhanVienName",
  NhanVienEmail: "NhanVienEmail",
  NhanVienNote: "NhanVienNote",
  MembershipID: "MembershipID",
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.",
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",
  LoginNotSuccess: "Đăng nhập không thành công.",
  UserNameExists: "UserName đã tồn tại.",
  UserNameRequired: "UserName là bắt buộc.",
};
