export const environment = {
  production: false, 
  DomainURL: "https://crm.vnptvungtau.vn/",  
  DomainDestination: "https://crm.vnptvungtau.vn/#/",  
  APIURL: "http://localhost:5227/swagger/api/v1/",    
  APIRootURL: "http://localhost:5227/swagger/",    
  APIUploadURL: "http://localhost:5227/api/v1/",    
  APIUploadRootURL: "http://localhost:5227/",    
  LoginURL: "https://login.vnptvungtau.vn/",
  Website: "https://vnptvungtau.vn/",
  Image: "Image",  
  Company: "Company", 
  Membership: "Membership", 
  Barcode: "Barcode",
  QRcode: "QRcode",
  OrderDelivery: "OrderDelivery", 
  OrderCall: "OrderCall", 
  Download: "Download",  
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  DialogConfigWidth60: "60%",  
  InitializationString: "",  
  InitializationNumber: 0, 
  CustomerID: 1, 
  ParentID: 1, 
  DieuHanhID: 2, 
  ShopID: 3, 
  ShipperID: 4, 
  ItemCount: 10, 
  CAID: 20,
  TenMienID: 42,
  HoaDonDienTuID: 14,
  Token: "Token", 
  OTP001: "OTP001",  
  NhanVienID: "NhanVienID",  
  NhanVienName: "NhanVienName",  
  NhanVienEmail: "NhanVienEmail",  
  NhanVienNote: "NhanVienNote",  
  AuthenticationToken: "AuthenticationToken",
  MembershipID: "MembershipID",  
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.", 
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",  
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",      
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",    
  LoginNotSuccess: "Đăng nhập không thành công.",    
  UserNameExists: "UserName đã tồn tại.",
  UserNameRequired: "UserName là bắt buộc.",    
};

